name: python-test
on: [pull_request]

jobs:
  python-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
      - name: Make envs for testing
        run: |
          echo "PINECONE_API_KEY=${{secrets.PINECONE_API_KEY}}" >> .env
          echo "PINECONE_ENVIRONMENT_REGION=${{secrets.PINECONE_ENVIRONMENT_REGION}}" >> .env
          echo "OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}" >> .env

      - name: Test code (pytest)
        run: |
          make test
